const apiKey: string = "9304018a";
export {apiKey}

export const types = {
    SEND_REQUEST : 'SEND_REQUEST',
    SEND_REQUEST_DETAILS : 'SEND_REQUEST_DETAILS',
    ADD_ALLRESULTS: 'ADD_ALLRESULTS',
    ADD_CURRENTPAGE: 'ADD_CURRENTPAGE',
    ADD_DETAILS: 'ADD_DETAILS',
    SET_FAVOURITES: 'SET_FAVOURITES',
    ADD_MOVIEID: 'ADD_MOVIEID',
    ADD_MOVIES: 'ADD_MOVIES',
    ADD_SEARCH: 'ADD_SEARCH'
}